### ISSUE TITLE
osError: Cannot detect RPI-Sense FB device

### ISSUE THREAD

**Issue by missteague** [RPi-Distro/python-sense-hat#42] opened 2016-03-10 13:18 UTC
I've tried everything I can think of and it's not working!

**Comment by XECDesign** [comment] 2016-03-11 17:08
Possible duplicate of #41 #38 or #28.

Could you please take a look at those issues and provide a bit more information? What have you tried?

**Comment by XECDesign** [comment] 2016-05-07 18:19
Inactive

**Closed by XECDesign** 2016-05-07 18:19 UTC
