### ISSUE TITLE
OSError: Cannot detect RPi-Sense FB device , 

### ISSUE THREAD

**Issue by Incarnation** [RPi-Distro/python-sense-hat#43] opened 2016-04-04 19:30 UTC
Hello would you please have a look at my issues: I have tried the following. Thanks.

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.1.20-v7+ #867 SMP Wed Mar 23 20:12:32 GMT 2016 armv7l GNU/Linux

pi@raspberrypi:~ $ vcgencmd version
Mar 24 2016 12:37:55 
Copyright (c) 2012 Broadcom
version e16cd015026a8bda22bb50dc30b30ce07f52a202 (clean) (release)

pi@raspberrypi:~ $ sudo dtc -I fs /proc/device-tree
Warning (avoid_default_addr_size): Relying on default #address-cells value for /axi/vc_mem
Warning (avoid_default_addr_size): Relying on default #size-cells value for /axi/vc_mem
/dts-v1/;

/ {
	model = "Raspberry Pi 3 Model B Rev 1.2";
	compatible = "brcm,bcm2710", "brcm,bcm2709";
	memreserve = <0x3b000000 0x4000000>;
	#address-cells = <0x1>;
	#size-cells = <0x1>;
	interrupt-parent = <0x1>;

	axi {

		dma {
			broadcom,channels = <0x7f35>;
		};

		usb {

			hub {

				ethernet {
					mac-address = [b8 27 eb 89 69 0f];
				};
			};
		};

		vc_mem {
			reg = <0x3dc00000 0x3f000000 0xc0000000>;
		};
	};

	soc {
		compatible = "simple-bus";
		ranges = <0x7e000000 0x3f000000 0x1000000>;
		#address-cells = <0x1>;
		phandle = <0x28>;
		#size-cells = <0x1>;
		linux,phandle = <0x28>;

		fb {
			compatible = "brcm,bcm2708-fb";
			firmware = <0x15>;
			status = "okay";
			phandle = <0x30>;
			linux,phandle = <0x30>;
		};

		mailbox@7e00b800 {
			reg = <0x7e00b880 0x40>;
			interrupts = <0x0 0x1>;
			compatible = "brcm,bcm2835-mbox";
			#mbox-cells = <0x0>;
			phandle = <0x13>;
			linux,phandle = <0x13>;
		};

		leds {
			compatible = "gpio-leds";
			phandle = <0x2f>;
			linux,phandle = <0x2f>;

			act {
				gpios = <0x14 0x0 0x0>;
				label = "led0";
				linux,default-trigger = "mmc0";
				phandle = <0x22>;
				linux,phandle = <0x22>;
			};
		};

		mmc@7e300000 {
			reg = <0x7e300000 0x100>;
			dmas = <0x8 0xb>;
			interrupts = <0x2 0x1e>;
			pinctrl-0 = <0x11>;
			compatible = "brcm,bcm2835-mmc";
			bus-width = <0x4>;
			clocks = <0x10>;
			non-removable;
			status = "okay";
			phandle = <0x2c>;
			brcm,overclock-50 = <0x0>;
			dma-names = "rx-tx";
			pinctrl-names = "default";
			linux,phandle = <0x2c>;
		};

		virtgpio {
			#gpio-cells = <0x2>;
			compatible = "brcm,bcm2835-virtgpio";
			firmware = <0x15>;
			status = "okay";
			phandle = <0x14>;
			gpio-controller;
			linux,phandle = <0x14>;
		};

		vchiq {
			reg = <0x7e00b840 0xf>;
			interrupts = <0x0 0x2>;
			compatible = "brcm,bcm2835-vchiq";
			cache-line-size = <0x40>;
			firmware = <0x15>;
			phandle = <0x16>;
			linux,phandle = <0x16>;
		};

		thermal {
			compatible = "brcm,bcm2835-thermal";
			firmware = <0x15>;
			phandle = <0x31>;
			linux,phandle = <0x31>;
		};

		firmware {
			compatible = "raspberrypi,bcm2835-firmware";
			mboxes = <0x13>;
			phandle = <0x15>;
			linux,phandle = <0x15>;
		};

		interrupt-controller@7e00b200 {
			reg = <0x7e00b200 0x200>;
			compatible = "brcm,bcm2708-armctrl-ic";
			#interrupt-cells = <0x2>;
			phandle = <0x1>;
			interrupt-controller;
			linux,phandle = <0x1>;
		};

		i2c@7e205000 {
			reg = <0x7e205000 0x1000>;
			interrupts = <0x2 0x15>;
			pinctrl-0 = <0xc>;
			compatible = "brcm,bcm2708-i2c";
			clock-frequency = <0x186a0>;
			clocks = <0x7>;
			status = "disabled";
			#address-cells = <0x1>;
			phandle = <0x1f>;
			#size-cells = <0x0>;
			pinctrl-names = "default";
			linux,phandle = <0x1f>;
		};

		dma@7e007000 {
			reg = <0x7e007000 0xf00>;
			interrupts = <0x1 0x10 0x1 0x11 0x1 0x12 0x1 0x13 0x1 0x14 0x1 0x15 0x1 0x16 0x1 0x17 0x1 0x18 0x1 0x19 0x1 0x1a 0x1 0x1b>;
			brcm,dma-channel-mask = <0xf35>;
			compatible = "brcm,bcm2835-dma";
			#dma-cells = <0x1>;
			phandle = <0x8>;
			linux,phandle = <0x8>;
		};

		usb@7e980000 {
			reg = <0x7e980000 0x10000 0x7e006000 0x1000>;
			interrupts = <0x2 0x0 0x1 0x9>;
			compatible = "brcm,bcm2708-usb";
			phandle = <0x2e>;
			linux,phandle = <0x2e>;
		};

		i2s@7e203000 {
			reg = <0x7e203000 0x24 0x7e101098 0x8>;
			pinctrl-0 = <0xa>;
			compatible = "brcm,bcm2708-i2s";
			status = "disabled";
			#sound-dai-cells = <0x0>;
			phandle = <0x1d>;
			dma-names = "tx", "rx";
			pinctrl-names = "default";
			linux,phandle = <0x1d>;
		};

		pwm@7e20c000 {
			reg = <0x7e20c000 0x28>;
			compatible = "brcm,bcm2835-pwm";
			clocks = <0xd>;
			#pwm-cells = <0x2>;
			status = "disabled";
			phandle = <0x2b>;
			linux,phandle = <0x2b>;
		};

		i2c@7e804000 {
			reg = <0x7e804000 0x1000>;
			interrupts = <0x2 0x15>;
			pinctrl-0 = <0x12>;
			compatible = "brcm,bcm2708-i2c";
			clock-frequency = <0x186a0>;
			clocks = <0x7>;
			status = "okay";
			#address-cells = <0x1>;
			phandle = <0x20>;
			#size-cells = <0x0>;
			pinctrl-names = "default";
			linux,phandle = <0x20>;
		};

		i2c@7e805000 {
			reg = <0x7e805000 0x1000>;
			interrupts = <0x2 0x15>;
			compatible = "brcm,bcm2708-i2c";
			clock-frequency = <0x186a0>;
			clocks = <0x7>;
			status = "disabled";
			#address-cells = <0x1>;
			phandle = <0x21>;
			#size-cells = <0x0>;
			linux,phandle = <0x21>;
		};

		cprman@7e101000 {
			reg = <0x7e101000 0x2000>;
			#clock-cells = <0x1>;
			compatible = "brcm,bcm2835-cprman";
			clocks = <0x2>;
			status = "disabled";
			phandle = <0x29>;
			linux,phandle = <0x29>;
		};

		gpiomem {
			reg = <0x7e200000 0x1000>;
			compatible = "brcm,bcm2835-gpiomem";
			status = "okay";
		};

		smi@7e600000 {
			reg = <0x7e600000 0x44 0x7e1010b0 0x8>;
			dmas = <0x8 0x4>;
			interrupts = <0x2 0x10>;
			brcm,smi-clock-source = <0x6>;
			compatible = "brcm,bcm2835-smi";
			brcm,smi-clock-divisor = <0x4>;
			status = "disabled";
			phandle = <0x2d>;
			dma-names = "rx-tx";
			linux,phandle = <0x2d>;
		};

		spi@7e204000 {
			reg = <0x7e204000 0x1000>;
			dmas = <0x8 0x6 0x8 0x7>;
			interrupts = <0x2 0x16>;
			pinctrl-0 = <0xb>;
			compatible = "brcm,bcm2835-spi";
			cs-gpios = <0x0 0x0>;
			clocks = <0x7>;
			status = "disabled";
			#address-cells = <0x1>;
			phandle = <0x1e>;
			#size-cells = <0x0>;
			dma-names = "tx", "rx";
			pinctrl-names = "default";
			linux,phandle = <0x1e>;

			spidev@0 {
				reg = <0x0>;
				compatible = "spidev";
				spi-max-frequency = <0x7a120>;
				#address-cells = <0x1>;
				#size-cells = <0x0>;
			};

			spidev@1 {
				reg = <0x1>;
				compatible = "spidev";
				spi-max-frequency = <0x7a120>;
				#address-cells = <0x1>;
				#size-cells = <0x0>;
			};
		};

		sdhost@7e202000 {
			reg = <0x7e202000 0x100>;
			dmas = <0x8 0xd>;
			interrupts = <0x2 0x18>;
			pinctrl-0 = <0x9>;
			compatible = "brcm,bcm2835-sdhost";
			brcm,pio-limit = <0x1>;
			bus-width = <0x4>;
			clocks = <0x7>;
			status = "okay";
			phandle = <0x26>;
			brcm,overclock-50 = <0x0>;
			dma-names = "rx-tx";
			pinctrl-names = "default";
			linux,phandle = <0x26>;
		};

		watchdog@7e100000 {
			reg = <0x7e100000 0x28>;
			compatible = "brcm,bcm2835-pm-wdt";
			status = "disabled";
			phandle = <0x24>;
			linux,phandle = <0x24>;
		};

		rng@7e104000 {
			reg = <0x7e104000 0x10>;
			compatible = "brcm,bcm2835-rng";
			status = "okay";
			phandle = <0x25>;
			linux,phandle = <0x25>;
		};

		arm-pmu {
			interrupts = <0x3 0x9>;
			compatible = "arm,cortex-a7-pmu";
		};

		gpio@7e200000 {
			reg = <0x7e200000 0xb4>;
			interrupts = <0x2 0x11 0x2 0x12>;
			#gpio-cells = <0x2>;
			compatible = "brcm,bcm2835-gpio";
			#interrupt-cells = <0x2>;
			phandle = <0x2a>;
			interrupt-controller;
			gpio-controller;
			linux,phandle = <0x2a>;

			i2s {
				phandle = <0xa>;
				brcm,function = <0x4>;
				brcm,pins = <0x12 0x13 0x14 0x15>;
				linux,phandle = <0xa>;
			};

			i2c0 {
				phandle = <0xc>;
				brcm,function = <0x4>;
				brcm,pins = <0x0 0x1>;
				linux,phandle = <0xc>;
			};

			i2c1 {
				phandle = <0x12>;
				brcm,function = <0x4>;
				brcm,pins = <0x2 0x3>;
				linux,phandle = <0x12>;
			};

			sdhost_pins {
				phandle = <0x9>;
				brcm,function = <0x4>;
				brcm,pins = <0x30 0x31 0x32 0x33 0x34 0x35>;
				linux,phandle = <0x9>;
			};

			sdio_pins {
				phandle = <0x11>;
				brcm,function = <0x7 0x7 0x7 0x7 0x7 0x7>;
				brcm,pins = <0x22 0x23 0x24 0x25 0x26 0x27>;
				brcm,pull = <0x0 0x2 0x2 0x2 0x2 0x2>;
				linux,phandle = <0x11>;
			};

			spi0_pins {
				phandle = <0xb>;
				brcm,function = <0x4>;
				brcm,pins = <0x7 0x8 0x9 0xa 0xb>;
				linux,phandle = <0xb>;
			};

			uart0_pins {
				phandle = <0x5>;
				brcm,function = <0x7>;
				brcm,pins = <0x20 0x21>;
				brcm,pull = <0x0 0x2>;
				linux,phandle = <0x5>;
			};

			uart1_pins {
				phandle = <0xf>;
				brcm,function;
				brcm,pins;
				brcm,pull;
				linux,phandle = <0xf>;
			};

			bt_pins {
				phandle = <0x6>;
				brcm,function = <0x4>;
				brcm,pins = <0x2b>;
				brcm,pull = <0x0>;
				linux,phandle = <0x6>;
			};
		};

		uart@7e201000 {
			reg = <0x7e201000 0x1000>;
			interrupts = <0x2 0x19>;
			pinctrl-0 = <0x5 0x6>;
			compatible = "arm,pl011", "arm,primecell";
			clock-names = "uartclk", "apb_pclk";
			clocks = <0x3 0x4>;
			status = "okay";
			arm,primecell-periphid = <0x241011>;
			phandle = <0x1b>;
			pinctrl-names = "default";
			linux,phandle = <0x1b>;
		};

		uart@7e215040 {
			reg = <0x7e215040 0x40>;
			interrupts = <0x1 0x1d>;
			pinctrl-0 = <0xf>;
			reg-shift = <0x2>;
			no-loopback-test;
			compatible = "brcm,bcm2835-aux-uart", "ns16550";
			clocks = <0xe>;
			status = "okay";
			phandle = <0x1c>;
			pinctrl-names = "default";
			linux,phandle = <0x1c>;
		};
	};

	cpus {
		#address-cells = <0x1>;
		phandle = <0x33>;
		#size-cells = <0x0>;
		linux,phandle = <0x33>;

		cpu@0 {
			reg = <0x0>;
			compatible = "arm,cortex-a7";
			clock-frequency = <0x47868c00>;
			device_type = "cpu";
			phandle = <0x17>;
			linux,phandle = <0x17>;
		};

		cpu@1 {
			reg = <0x1>;
			compatible = "arm,cortex-a7";
			clock-frequency = <0x47868c00>;
			device_type = "cpu";
			phandle = <0x18>;
			linux,phandle = <0x18>;
		};

		cpu@2 {
			reg = <0x2>;
			compatible = "arm,cortex-a7";
			clock-frequency = <0x47868c00>;
			device_type = "cpu";
			phandle = <0x19>;
			linux,phandle = <0x19>;
		};

		cpu@3 {
			reg = <0x3>;
			compatible = "arm,cortex-a7";
			clock-frequency = <0x47868c00>;
			device_type = "cpu";
			phandle = <0x1a>;
			linux,phandle = <0x1a>;
		};
	};

	display {
		broadcom,height = <0x0>;
		broadcom,depth = <0x10>;
		broadcom,width = <0x0>;
	};

	audio {
		compatible = "brcm,bcm2835-audio";
		status = "okay";
		brcm,pwm-channels = <0x8>;
		phandle = <0x23>;
		linux,phandle = <0x23>;
	};

	sound {
		phandle = <0x27>;
		linux,phandle = <0x27>;
	};

	timer {
		interrupts = <0x3 0x0 0x3 0x1 0x3 0x3 0x3 0x2>;
		compatible = "arm,armv7-timer";
		clock-frequency = <0x124f800>;
		always-on;
	};

	chosen {
		bootargs = "8250.nr_uarts=1 dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2709.boardrev=0xa02082 bcm2709.serial=0x3a89690f smsc95xx.macaddr=B8:27:EB:89:69:0F bcm2708_fb.fbswap=1 bcm2709.uart_clock=48000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait", "t";
	};

	clocks {
		compatible = "simple-bus";
		#address-cells = <0x1>;
		phandle = <0x32>;
		#size-cells = <0x0>;
		linux,phandle = <0x32>;

		clock@0 {
			reg = <0x0>;
			#clock-cells = <0x0>;
			compatible = "fixed-clock";
			clock-frequency = <0x17d78400>;
			clock-output-names = "core";
			phandle = <0x7>;
			linux,phandle = <0x7>;
		};

		clock@1 {
			reg = <0x1>;
			#clock-cells = <0x0>;
			compatible = "fixed-clock";
			clock-frequency = <0xee6b280>;
			clock-output-names = "mmc";
			phandle = <0x10>;
			linux,phandle = <0x10>;
		};

		clock@2 {
			reg = <0x2>;
			#clock-cells = <0x0>;
			compatible = "fixed-clock";
			clock-frequency = <0x2dc6c00>;
			clock-output-names = "uart0_pclk";
			phandle = <0x3>;
			linux,phandle = <0x3>;
		};

		clock@3 {
			reg = <0x3>;
			#clock-cells = <0x0>;
			compatible = "fixed-clock";
			clock-frequency = <0x7829b80>;
			clock-output-names = "apb_pclk";
			phandle = <0x4>;
			linux,phandle = <0x4>;
		};

		clock@4 {
			reg = <0x4>;
			#clock-cells = <0x0>;
			compatible = "fixed-clock";
			clock-frequency = <0x5f5e100>;
			clock-output-names = "pwm";
			phandle = <0xd>;
			linux,phandle = <0xd>;
		};

		clock@5 {
			reg = <0x5>;
			#clock-cells = <0x0>;
			compatible = "fixed-factor-clock";
			clocks = <0x7>;
			clock-div = <0x1>;
			phandle = <0xe>;
			clock-mult = <0x2>;
			linux,phandle = <0xe>;
		};

		clock@6 {
			reg = <0x6>;
			#clock-cells = <0x0>;
			compatible = "fixed-clock";
			clock-frequency = <0x124f800>;
			clock-output-names = "osc";
			phandle = <0x2>;
			linux,phandle = <0x2>;
		};
	};

	memory {
		reg = <0x0 0x3b000000>;
		device_type = "memory";
	};

	system {
		linux,revision = <0xa02082>;
		linux,serial = <0x0 0x3a89690f>;
	};

	__symbols__ {
		fb = "/soc/fb";
		i2c = "/soc/i2c@7e804000";
		i2s = "/soc/i2s@7e203000";
		dma = "/soc/dma@7e007000";
		mmc = "/soc/mmc@7e300000";
		pwm = "/soc/pwm@7e20c000";
		smi = "/soc/smi@7e600000";
		soc = "/soc";
		usb = "/soc/usb@7e980000";
		cpus = "/cpus";
		i2c0 = "/soc/i2c@7e205000";
		i2c1 = "/soc/i2c@7e804000";
		i2c2 = "/soc/i2c@7e805000";
		gpio = "/soc/gpio@7e200000";
		intc = "/soc/interrupt-controller@7e00b200";
		leds = "/soc/leds";
		spi0 = "/soc/spi@7e204000";
		v7_cpu0 = "/cpus/cpu@0";
		v7_cpu1 = "/cpus/cpu@1";
		v7_cpu2 = "/cpus/cpu@2";
		v7_cpu3 = "/cpus/cpu@3";
		i2c_arm = "/soc/i2c@7e804000";
		virtgpio = "/soc/virtgpio";
		audio = "/audio";
		sound = "/sound";
		uart0 = "/soc/uart@7e201000";
		uart1 = "/soc/uart@7e215040";
		vchiq = "/soc/vchiq";
		sdhost_pins = "/soc/gpio@7e200000/sdhost_pins";
		sdio_pins = "/soc/gpio@7e200000/sdio_pins";
		i2s_pins = "/soc/gpio@7e200000/i2s";
		mailbox = "/soc/mailbox@7e00b800";
		thermal = "/soc/thermal";
		clocks = "/clocks";
		firmware = "/soc/firmware";
		cprman = "/soc/cprman@7e101000";
		i2c_vc = "/soc/i2c@7e205000";
		watchdog = "/soc/watchdog@7e100000";
		i2c0_pins = "/soc/gpio@7e200000/i2c0";
		i2c1_pins = "/soc/gpio@7e200000/i2c1";
		act_led = "/soc/leds/act";
		random = "/soc/rng@7e104000";
		spi0_pins = "/soc/gpio@7e200000/spi0_pins";
		sdhost = "/soc/sdhost@7e202000";
		uart0_pins = "/soc/gpio@7e200000/uart0_pins";
		uart1_pins = "/soc/gpio@7e200000/uart1_pins";
		clk_apb_p = "/clocks/clock@3";
		clk_uart0 = "/clocks/clock@2";
		clk_uart1 = "/clocks/clock@5";
		bt_pins = "/soc/gpio@7e200000/bt_pins";
		clk_core = "/clocks/clock@0";
		clk_mmc = "/clocks/clock@1";
		clk_osc = "/clocks/clock@6";
		clk_pwm = "/clocks/clock@4";
	};

	aliases {
		fb = "/soc/fb";
		i2c = "/soc/i2c@7e804000";
		i2s = "/soc/i2s@7e203000";
		dma = "/soc/dma@7e007000";
		mmc = "/soc/mmc@7e300000";
		soc = "/soc";
		usb = "/soc/usb@7e980000";
		i2c0 = "/soc/i2c@7e205000";
		i2c1 = "/soc/i2c@7e804000";
		i2c2 = "/soc/i2c@7e805000";
		gpio = "/soc/gpio@7e200000";
		intc = "/soc/interrupt-controller@7e00b200";
		leds = "/soc/leds";
		spi0 = "/soc/spi@7e204000";
		i2c_arm = "/soc/i2c@7e804000";
		audio = "/audio";
		sound = "/sound";
		uart0 = "/soc/uart@7e201000";
		uart1 = "/soc/uart@7e215040";
		vchiq = "/soc/vchiq";
		serial0 = "/soc/uart@7e215040";
		serial1 = "/soc/uart@7e201000";
		mailbox = "/soc/mailbox@7e00b800";
		thermal = "/soc/thermal";
		clocks = "/clocks";
		i2c_vc = "/soc/i2c@7e205000";
		watchdog = "/soc/watchdog@7e100000";
		random = "/soc/rng@7e104000";
		sdhost = "/soc/sdhost@7e202000";
	};

	__overrides__ {
		i2c = "", "", "", " status";
		i2s = [00 00 00 1d 73 74 61 74 75 73 00];
		spi = [00 00 00 1e 73 74 61 74 75 73 00];
		act_led_trigger = "", "", "", "\"linux,default-trigger";
		i2c0 = [00 00 00 1f 73 74 61 74 75 73 00];
		i2c1 = "", "", "", " status";
		i2c_arm = "", "", "", " status";
		audio = "", "", "", "#status";
		uart0 = [00 00 00 1b 73 74 61 74 75 73 00];
		uart1 = [00 00 00 1c 73 74 61 74 75 73 00];
		i2c2_iknowwhatimdoing = "", "", "", "!status";
		act_led_activelow = "", "", "", "\"gpios:8";
		i2c0_baudrate = [00 00 00 1f 63 6c 6f 63 6b 2d 66 72 65 71 75 65 6e 63 79 3a 30 00];
		sd_overclock = "", "", "", "&brcm,overclock-50:0";
		sd_pio_limit = "", "", "", "&brcm,pio-limit:0";
		sd_debug = "", "", "", "&brcm,debug";
		i2c_vc_baudrate = [00 00 00 1f 63 6c 6f 63 6b 2d 66 72 65 71 75 65 6e 63 79 3a 30 00];
		uart0_clkrate = [00 00 00 03 63 6c 6f 63 6b 2d 66 72 65 71 75 65 6e 63 79 3a 30 00];
		i2c_vc = [00 00 00 1f 73 74 61 74 75 73 00];
		i2c1_baudrate = "", "", "", " clock-frequency:0";
		i2c_baudrate = "", "", "", " clock-frequency:0";
		watchdog = "", "", "", "$status";
		sd_force_pio = "", "", "", "&brcm,force-pio?";
		random = "", "", "", "%status";
		arm_freq = <0x17 0x636c6f63 0x6b2d6672 0x65717565 0x6e63793a 0x30000000 0x18636c 0x6f636b2d 0x66726571 0x75656e63 0x793a3000 0x19 0x636c6f63 0x6b2d6672 0x65717565 0x6e63793a 0x30000000 0x1a636c 0x6f636b2d 0x66726571 0x75656e63 0x793a3000>;
		i2c2_baudrate = "", "", "", "!clock-frequency:0";
		core_freq = "", "", "", "\aclock-frequency:0";
		i2c_arm_baudrate = "", "", "", " clock-frequency:0";
		act_led_gpio = "", "", "", "\"gpios:4";
		cache_line_size = [00 00 00 16 63 61 63 68 65 2d 6c 69 6e 65 2d 73 69 7a 65 3a 30 00];
	};
};

**Comment by XECDesign** [comment] 2016-04-05 13:56
Does it work if you add `dtoverlay=rpi-sense` to `/boot/config.txt`?

**Comment by Incarnation** [comment] 2016-04-05 14:24
yes I added that and works! Thanks a lot. :)

**Comment by XECDesign** [comment] 2016-04-05 14:29
Np. In that case, this is a duplicate of #28.

**Closed by XECDesign** 2016-04-05 14:29 UTC
